version: '3'

services:
    data-service:
        build: ./
        volumes: 
            - ./:/home
        command: 
            python /home/download_data_csv.py

    website-service:
        image: nginx
        volumes: 
            - ./:/usr/share/nginx/html
        ports:
            - 7000:80
        depends_on:
            - data-service
