version: "3.0"
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.4.2
    environment:
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms64m -Xmx512m"
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ~/mydata/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ~/mydata/elasticsearch/data:/usr/share/elasticsearch/data
      - ~/mydata/elasticsearch/plugins:/usr/share/elasticsearch/plugins
  kibana:
    container_name: kibana
    image: kibana:7.4.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  es-net:
    driver: bridge
