name: jd-optimizer (dev)

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build, tag and scan docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t dhutsj/test:$IMAGE_TAG .
          docker scout cves dhutsj/test:$IMAGE_TAG
          docker scout recommendations dhutsj/test:$IMAGE_TAG
        #   docker push dhutsj/test:$IMAGE_TAG
