name: docker-build-scan

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build, tag and scan docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t dhutsj/test:$IMAGE_TAG .
        #   docker push dhutsj/test:$IMAGE_TAG
      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
            command: cves
            image: dhutsj/test:$IMAGE_TAG
            only-severities: critical,high
            exit-code: true
