name: docker-build-scan

on:
  push:
    branches:
      - 'master'

env:
  REGISTRY: docker.io
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, tag and scan docker image
        run: |
          docker build -t dhutsj/test:$IMAGE_TAG .
        #   docker push dhutsj/test:$IMAGE_TAG
      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: cves
          image: dhutsj/test:$IMAGE_TAG
          only-severities: critical,high
          exit-code: true
